# -*- coding: utf-8 -*-
"""YOLO V8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1raiCdiPJXvieZmaa4LrCDzqEZ4l9cQcX
"""

!pip install ultralytics

from google.colab import drive
drive.mount('/content/drive')

from ultralytics import YOLO

model = YOLO('yolov8n-cls.pt')  # load a pretrained YOLOv8n classification model
model.train(data='/content/drive/MyDrive/SAR', epochs=20)  # train the model

model('/content/drive/MyDrive/SAR/validation/Cricket/frame 0 (169).png')  # predict on an image

# Validate the model
metrics = model.val() # no arguments needed, dataset and settings remembered
metrics.top1 # top1 accuracy
metrics.top5 # top5 accuracy

results = model.predict('/content/drive/MyDrive/SAR/validation/Swimming/frame 0 (277).png')









